### ISSUE TITLE
SERVICE CROSS-CHECK LISTS

### ISSUE THREAD

**Issue by npetheriot** [Joshua-Chiu/PGDBWebServer#31]
I'm starting to use the cross-check lists and have discovered that the page isn't wide enough to list all the service that some students have done.  SO, their service gets cuts off after 10 entries.  What can we do to fix this?  Also, the cross-check list FONT is extremely small and difficult to read because the students with too many submission cause the report to get wider and wider.  I'm an old guy and have a hard time with the tiny font.  lol  The bigger concern is that many students entries go beyond the page and just get cut off...so they're impossible to see.  How can we modify this report to make it more user friendly?  1. larger font 2. display all entries (unlimited)

**Comment by Joshua-Chiu** [comment]
I am having some serious issues with all of the service reports...the service crosscheck, the service trophy lists, the graduation service report.... We knew that this was an existing problem however it does now need to be fixed. Because the reports auto-adjust on horizontal size/length, the font shrinks the wider the report gets. I am now in the process of having to cross-check my service entries and the report I've printed is in super tiny font. It is so small that I can't make it out. We have to find a way to put a carriage return after probably 5 service entries. Please?

**Comment by Joshua-Chiu** [comment]
Printer driver and OS problem.
